
import Head from 'next/head'
import Features from './Features'
import {Swiper, SwiperSlide} from "swiper/react";
import Card from './card';
import { Card1 } from './card';
import {Keyboard, Pagination, Navigation} from "swiper";
import CardProps2 from '@/components/card_props2'
import Layout from '@/components/layout';
import PictureCard from './picturecard';
import Mainpage, { MainPage1 } from './mainpage';
import 'swiper/css';
import { useRef } from 'react';
export default function Home() {
  
  
  return (
    <>
      <Head>
        <title>Cosme</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>

        <Features/>
      </Layout>
    </>
  )
}
