
import Head from 'next/head'
import Features from './Features'
import {Swiper, SwiperSlide} from "swiper/react";
import Card from './card';
import { Card1 } from './card';
import {Keyboard, Pagination, Navigation} from "swiper";
import CardProps2 from '@/components/card_props2'
import Layout from '@/components/layout';

import 'swiper/css';

export default function Home({data}) {

 
  
  return (
    <>
      <Head>
        <title>Cosme</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <Swiper
      direction={"vertical"}
      
      slidesPerView={1}
      height = {"1580"}

      keyboard={{
        enabled: true,
      }}
      modules={[Keyboard, Pagination, Navigation]}
    >
        {data.map((post) => (
           <SwiperSlide>
           <Features userName = {post} content = {post}/> 
         </SwiperSlide>
        ))}
         
       
      
        </Swiper>
      </Layout>
    </>
  )
}


export async function getServerSideProps(){
  const res = await fetch(`http://34.133.106.148:5000/routine`);
  const data = await res.json();

  return{
    props: data,

  };

}