
import Head from 'next/head'
import Layout from '@/components/layout';
import 'swiper/css';
import GPT from './chatgpt';
import Login from './login';
import { BrowserRouter, Route, Routes } from "react-router-dom";

export default function Home({projects}) {
 
 
  return (
    <>
      <Head>
        <title>Cosme</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
        
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*<Layout>*/}
        
       <div className="container mx-auto py-5 px-4">
      <div className="flex flex-wrap">
     
      
       <Login/>
     
      </div>
      </div>
      
     
       
      {/*</Layout>*/}
    </>
  )
}


